// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbuZyrVwX2J6fEDtk-T6KhEG6LqTfg8AM',
    appId: '1:236092483005:web:7864db0fbd50f02b8f5ed4',
    messagingSenderId: '236092483005',
    projectId: 'bitirme-projesi-flutter',
    authDomain: 'bitirme-projesi-flutter.firebaseapp.com',
    storageBucket: 'bitirme-projesi-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNUa53EfVU2eIQHF3qHjYps0eg1Ny2FNA',
    appId: '1:236092483005:android:69c25fdedd1ce19c8f5ed4',
    messagingSenderId: '236092483005',
    projectId: 'bitirme-projesi-flutter',
    storageBucket: 'bitirme-projesi-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIPdh5NqwZWLYgLF2uNGKQcEusKI_vRlw',
    appId: '1:236092483005:ios:7f6b70d74c591d218f5ed4',
    messagingSenderId: '236092483005',
    projectId: 'bitirme-projesi-flutter',
    storageBucket: 'bitirme-projesi-flutter.appspot.com',
    iosClientId: '236092483005-mev4hihd2f98rc4k4umhtqs5l8ehfnu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBitirmeProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIPdh5NqwZWLYgLF2uNGKQcEusKI_vRlw',
    appId: '1:236092483005:ios:7f6b70d74c591d218f5ed4',
    messagingSenderId: '236092483005',
    projectId: 'bitirme-projesi-flutter',
    storageBucket: 'bitirme-projesi-flutter.appspot.com',
    iosClientId: '236092483005-mev4hihd2f98rc4k4umhtqs5l8ehfnu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBitirmeProje',
  );
}
